Feat/멤버엔티티
jaws-projects/jaws pull request #3
Opened 2024-02-06 06:33 UTC by Drum-J

## 작업 내용
Member 엔티티를 추가했습니다.
Study 엔티티는 단순하게 연관관계 매핑을 위해 Id 와 Member만 가지게끔 생성했습니다.
(Board를 Study 로 임의로 설정했습니다. 혹시 다른 이름 생각나시면 말씀해주세요!)

API 테스트를 위해서 Controller/Service/Repository/Dto도 생성했습니다!

## 관련 이슈
close #2 

## 기타
회의 때 스터디 모집글을 어떻게 할 지 몰라서 Board로 했었는데 일단 Study로 생성해두긴 했습니다.

테스트 코드는 경현님이 말씀해 주신 것처럼 로직을 테스트하는 걸로 작성하긴 했는데 이렇게 하는 게 맞을까요...?

2024-02-06 07:02 UTC, kyunghyun-Park commented
오늘 꼭 확인해볼게요!

2024-02-06 14:55 UTC, kyunghyun-Park requested changes
제가 배운거 토대로 리뷰해봤는데 첫 리뷰라 어설프네요..
저도 `Board`보다는 `Study`네이밍이 더 좋은 것 같아요.

테스트 코드는 전반적으로 잘 작성하신 것 같은데, 제가 getter사용에서 헷갈리는 게 있어서 좀 더 찾아보고 슬랙에 말씀드릴게요!

2024-02-06 14:55 UTC, kyunghyun-Park commented on src/main/java/com/jaws/entitiy/Member.java
> +    // 업데이트 메서드
이 주석의 용도는 무엇인가요?🤔

2024-02-06 14:55 UTC, kyunghyun-Park commented on src/main/java/com/jaws/entitiy/Study.java
> +        member.getStudies().add(this);
[디미터의 법칙](https://mangkyu.tistory.com/147)을 참고해서 member가 직접 add하는 책임을 지도록 member에게 메시지를 보내면 좋을 것 같아요!

2024-02-06 14:55 UTC, kyunghyun-Park commented on src/main/java/com/jaws/member/dto/MemberResponseDto.java
> +    }
적절한 개행으로 가독성을 높여보시면 좋을 것 같아요.

2024-02-06 14:55 UTC, kyunghyun-Park commented on src/main/java/com/jaws/entitiy/Member.java
> +    private List<Study> studies = new ArrayList<>();
변수명으로 자료구조명을 사용하지 않는거 좋네요👍

2024-02-06 14:55 UTC, kyunghyun-Park commented on src/main/java/com/jaws/study/service/StudyService.java
> +                .orElseThrow(() -> new IllegalArgumentException("해당 스터디를 찾을 수 없습니다."));
비슷한 예외에 대해서 저희만의 예외 전략을 사용하는것도 좋을 것 같아요!
지금은 말고 예외가 더 많아지면 리팩토링 해봅시다!

💡
[Java의 Error와 Exception 그리고 예외처리 전략](https://toneyparky.tistory.com/40)

2024-02-06 14:55 UTC, kyunghyun-Park commented on src/test/java/com/jaws/entity/MemberTest.java
> +        Member member1 = new Member("test@email.com", "승호");
변수명에 숫자를 사용하는 것은 지양해야 한다고 해요 ㅠㅠ
가볍게 읽어보시면 좋을 것 같아요

💡
[좋은 코드를 위한 자바 변수명 네이밍](https://tecoble.techcourse.co.kr/post/2020-04-24-variable_naming/)
[프로그래밍에서 변수 명 짓기의 중요성 및 팁](https://www.ibatstudio.com/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D%EC%97%90%EC%84%9C-%EB%B3%80%EC%88%98-%EB%AA%85-%EC%A7%93%EA%B8%B0%EC%9D%98-%EC%A4%91%EC%9A%94%EC%84%B1-%EB%B0%8F-%ED%8C%81/)

2024-02-06 14:55 UTC, kyunghyun-Park commented on src/test/java/com/jaws/entity/StudyTest.java
> +        assertThat(member.getStudies().contains(study)).isTrue();
테스트당 assert문은 하나만 있는 게 좋을 것 같아요!
불가피할 경우 `assertAll()`이나 `assertSoftly()`쓰는 게 좋다고 하네용


💡
[테스트를 작성하는 방법](https://blog.kingbbode.com/52)

2024-02-06 14:55 UTC, kyunghyun-Park commented on src/test/java/com/jaws/entity/StudyTest.java
> +    }
메서드 재사용 너무 좋은데요!

2024-02-07 05:57 UTC, Drum-J commented on src/main/java/com/jaws/entitiy/Member.java
> +    // 업데이트 메서드
아 이거는 습관입니다... 
엔티티에 비즈니스 로직이 더 쌓였을 때 주석으로 그룹(?)을 나눠두기 위한거에요!

현재 Member 엔티티에는 updateNickname(업데이트 메서드) , removeStudy(연관관계 제거 메서드) 이렇게 밖에 없는데 나중에 더 쌓였을때 헷갈리지 말라고 주석으로 작성중이에요!

나중에 리팩토링 할 때 주석 제거하면 될 것 같아용

2024-02-07 05:58 UTC, Drum-J commented on src/main/java/com/jaws/entitiy/Study.java
> +        member.getStudies().add(this);
강의 들을때도 이렇게 get으로 가져와서 하는것보다 member가 직접 처리하도록 호출하는게 좋지 않나..? 했었는데 이런 법칙도 있었네요! 참고해서 코드 수정해보도록 하겠습니다!

2024-02-07 05:58 UTC, Drum-J commented on src/main/java/com/jaws/entitiy/Member.java
> +    private List<Study> studies = new ArrayList<>();
저번에 알려주셨던거 적용해봤습니다! :)

2024-02-07 05:58 UTC, Drum-J commented on src/main/java/com/jaws/study/service/StudyService.java
> +                .orElseThrow(() -> new IllegalArgumentException("해당 스터디를 찾을 수 없습니다."));
맞아요! 지금은 따로 예외를 만들지 않아서 간단하게 구현했습니다. 이 부분은 따로 체크해 두는 게 좋겠네요.

2024-02-07 06:01 UTC, Drum-J commented on src/test/java/com/jaws/entity/StudyTest.java
> +        assertThat(member.getStudies().contains(study)).isTrue();
오 감사합니다!! 아는게 저거밖에 없어서 저렇게 줄줄 쓰면서도 좀 그렇다 생각했는데... ㅋㅋㅋ 테스트도 더 공부해야겠어요

2024-02-07 06:24 UTC, kyunghyun-Park commented on src/test/java/com/jaws/entity/StudyTest.java
> +        assertThat(member.getStudies().contains(study)).isTrue();
`hashCode()`, `equals()` 추가해서 이런식으로 객체끼리 비교하라고 배운 것 같은데.. 우테코랑 많이 다르네요
저도 공부해야겠어요 ㅠㅠ 
```suggestion
        Member updatedMember= new Member("변경된 승호");
        assertThat(member).isEqualTo(updatedMember);
```

2024-02-07 06:29 UTC, kyunghyun-Park commented on src/main/java/com/jaws/entitiy/Study.java
> +        member.getStudies().add(this);
오 그걸 먼저 인지하시다니.. 천재만재십니다

2024-02-07 07:03 UTC, merged